/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'
import { Route as AnimeAnimeIdIndexRouteImport } from './routes/anime/$animeId.index'
import { Route as ApiAnisourceSplatRouteImport } from './routes/api/anisource/$'
import { Route as MangaMangaIdIndexRouteImport } from './routes/manga/$mangaId.index'
import { Route as AnimeAnimeIdWatchEpisodeIdRouteImport } from './routes/anime/$animeId.watch.$episodeId'
import { Route as MangaMangaIdReadChapterNumberRouteImport } from './routes/manga/$mangaId.read.$chapterNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdIndexRoute = AnimeAnimeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeAnimeIdRoute,
} as any)
const ApiAnisourceSplatRoute = ApiAnisourceSplatRouteImport.update({
  id: '/api/anisource/$',
  path: '/api/anisource/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaMangaIdIndexRoute = MangaMangaIdIndexRouteImport.update({
  id: '/manga/$mangaId/',
  path: '/manga/$mangaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdWatchEpisodeIdRoute =
  AnimeAnimeIdWatchEpisodeIdRouteImport.update({
    id: '/watch/$episodeId',
    path: '/watch/$episodeId',
    getParentRoute: () => AnimeAnimeIdRoute,
  } as any)
const MangaMangaIdReadChapterNumberRoute =
  MangaMangaIdReadChapterNumberRouteImport.update({
    id: '/manga/$mangaId/read/$chapterNumber',
    path: '/manga/$mangaId/read/$chapterNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/api/anisource/$': typeof ApiAnisourceSplatRoute
  '/anime/$animeId/': typeof AnimeAnimeIdIndexRoute
  '/manga/$mangaId/': typeof MangaMangaIdIndexRoute
  '/anime/$animeId/watch/$episodeId': typeof AnimeAnimeIdWatchEpisodeIdRoute
  '/manga/$mangaId/read/$chapterNumber': typeof MangaMangaIdReadChapterNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/api/anisource/$': typeof ApiAnisourceSplatRoute
  '/anime/$animeId': typeof AnimeAnimeIdIndexRoute
  '/manga/$mangaId': typeof MangaMangaIdIndexRoute
  '/anime/$animeId/watch/$episodeId': typeof AnimeAnimeIdWatchEpisodeIdRoute
  '/manga/$mangaId/read/$chapterNumber': typeof MangaMangaIdReadChapterNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/anime/$animeId': typeof AnimeAnimeIdRouteWithChildren
  '/api/anisource/$': typeof ApiAnisourceSplatRoute
  '/anime/$animeId/': typeof AnimeAnimeIdIndexRoute
  '/manga/$mangaId/': typeof MangaMangaIdIndexRoute
  '/anime/$animeId/watch/$episodeId': typeof AnimeAnimeIdWatchEpisodeIdRoute
  '/manga/$mangaId/read/$chapterNumber': typeof MangaMangaIdReadChapterNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/anime/$animeId'
    | '/api/anisource/$'
    | '/anime/$animeId/'
    | '/manga/$mangaId/'
    | '/anime/$animeId/watch/$episodeId'
    | '/manga/$mangaId/read/$chapterNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/api/anisource/$'
    | '/anime/$animeId'
    | '/manga/$mangaId'
    | '/anime/$animeId/watch/$episodeId'
    | '/manga/$mangaId/read/$chapterNumber'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/library'
    | '/profile'
    | '/schedule'
    | '/settings'
    | '/anime/$animeId'
    | '/api/anisource/$'
    | '/anime/$animeId/'
    | '/manga/$mangaId/'
    | '/anime/$animeId/watch/$episodeId'
    | '/manga/$mangaId/read/$chapterNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRouteWithChildren
  ApiAnisourceSplatRoute: typeof ApiAnisourceSplatRoute
  MangaMangaIdIndexRoute: typeof MangaMangaIdIndexRoute
  MangaMangaIdReadChapterNumberRoute: typeof MangaMangaIdReadChapterNumberRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/': {
      id: '/anime/$animeId/'
      path: '/'
      fullPath: '/anime/$animeId/'
      preLoaderRoute: typeof AnimeAnimeIdIndexRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/api/anisource/$': {
      id: '/api/anisource/$'
      path: '/api/anisource/$'
      fullPath: '/api/anisource/$'
      preLoaderRoute: typeof ApiAnisourceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$mangaId/': {
      id: '/manga/$mangaId/'
      path: '/manga/$mangaId'
      fullPath: '/manga/$mangaId/'
      preLoaderRoute: typeof MangaMangaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId/watch/$episodeId': {
      id: '/anime/$animeId/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/anime/$animeId/watch/$episodeId'
      preLoaderRoute: typeof AnimeAnimeIdWatchEpisodeIdRouteImport
      parentRoute: typeof AnimeAnimeIdRoute
    }
    '/manga/$mangaId/read/$chapterNumber': {
      id: '/manga/$mangaId/read/$chapterNumber'
      path: '/manga/$mangaId/read/$chapterNumber'
      fullPath: '/manga/$mangaId/read/$chapterNumber'
      preLoaderRoute: typeof MangaMangaIdReadChapterNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AnimeAnimeIdRouteChildren {
  AnimeAnimeIdIndexRoute: typeof AnimeAnimeIdIndexRoute
  AnimeAnimeIdWatchEpisodeIdRoute: typeof AnimeAnimeIdWatchEpisodeIdRoute
}

const AnimeAnimeIdRouteChildren: AnimeAnimeIdRouteChildren = {
  AnimeAnimeIdIndexRoute: AnimeAnimeIdIndexRoute,
  AnimeAnimeIdWatchEpisodeIdRoute: AnimeAnimeIdWatchEpisodeIdRoute,
}

const AnimeAnimeIdRouteWithChildren = AnimeAnimeIdRoute._addFileChildren(
  AnimeAnimeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRouteWithChildren,
  ApiAnisourceSplatRoute: ApiAnisourceSplatRoute,
  MangaMangaIdIndexRoute: MangaMangaIdIndexRoute,
  MangaMangaIdReadChapterNumberRoute: MangaMangaIdReadChapterNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
