import { For, Show } from 'solid-js'
import type { AniListDetail } from '../../../data/anilist/types'
import type { AniSourceAnime } from '../../../data/anisource/schema'
import type { RankedCandidate, TitleVariant } from '../../../data/matching'
import { titleOf } from '../../../lib/format'

interface MatchPickerProps { anime: AniListDetail; sourceName: string; variants: TitleVariant[]; ranked: RankedCandidate[]; query: string; loading: boolean; onQuery: (value: string) => void; onVariantSearch: (title: string) => void; onChoose: (candidate: AniSourceAnime) => void }

export function MatchPicker(props: MatchPickerProps) {
  const cover = () => props.anime.coverImage?.extraLarge ?? props.anime.coverImage?.large ?? ''
  return <section class="mb-6 rounded-shell border border-white/75 bg-white/62 p-5 shadow-glass backdrop-blur-[40px] sm:p-6" aria-labelledby="match-picker-title">
    <div class="grid gap-5 sm:grid-cols-[96px_1fr]"><Show when={cover()} fallback={<div class="grid aspect-[2/3] w-24 place-items-center bg-black font-display text-4xl text-white">✦</div>}><img class="aspect-[2/3] w-24 object-cover" src={cover()} alt={`${titleOf(props.anime)} cover`} width="96" height="144" /></Show><div><p class="font-mono text-[9px] uppercase tracking-[.16em] text-[#4f4e57]">Match assist / {props.sourceName}</p><h2 id="match-picker-title" class="mt-1 font-display text-4xl leading-none">Find {titleOf(props.anime)}</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-[#42404b]">Choose the closest catalog title, or search this source using an alternate AniList title.</p></div></div>
    <div class="mt-6 border-t border-black/12 pt-5"><p class="font-mono text-[9px] uppercase tracking-[.16em] text-[#4f4e57]">Try a title</p><div class="mt-2 flex flex-wrap gap-2"><For each={props.variants}>{(variant) => <button class="border border-black/18 bg-white px-3 py-2 text-left text-xs font-semibold transition hover:border-black hover:bg-black hover:text-white" type="button" onClick={() => props.onVariantSearch(variant.title)}><span class="font-mono text-[9px] uppercase tracking-[.1em] opacity-55">{variant.label}</span> · {variant.title}</button>}</For></div></div>
    <form class="mt-5 rounded-[14px] border border-black/10 bg-white/45 p-4" onSubmit={(event) => { event.preventDefault(); props.onVariantSearch(props.query) }}><label class="font-mono text-[9px] uppercase tracking-[.16em] text-[#4f4e57]" for="manual-match-search">Search {props.sourceName} manually</label><div class="mt-2 flex gap-2"><input id="manual-match-search" class="h-10 min-w-0 flex-1 rounded-[10px] border border-black/18 bg-white/78 px-3 text-sm outline-none focus:border-black" type="search" placeholder="Try a custom title…" value={props.query} onInput={(event) => props.onQuery(event.currentTarget.value)} /><button class="rounded-[10px] border border-black bg-black px-4 font-mono text-[10px] uppercase tracking-[.1em] text-white disabled:cursor-not-allowed disabled:opacity-40" type="submit" disabled={props.loading || props.query.trim().length < 2}>Search</button></div></form>
    <p class="mt-4 font-mono text-[10px] uppercase tracking-[.1em] text-[#42404b]" aria-live="polite">{props.loading ? `Searching ${props.sourceName}…` : props.ranked.length ? `${props.ranked.length} possible matches` : 'No results yet — try searching manually.'}</p>
    <div class="mt-3 grid gap-px overflow-hidden rounded-[14px] border border-black/12 bg-black/12 sm:grid-cols-2"><For each={props.ranked}>{(entry) => <button class="flex gap-3 bg-white p-3 text-left transition hover:bg-black hover:text-white" type="button" onClick={() => props.onChoose(entry.candidate)}><Show when={entry.candidate.thumbnail} fallback={<div class="grid aspect-[2/3] w-14 place-items-center bg-black font-display text-xl text-white">✦</div>}><img class="aspect-[2/3] w-14 object-cover" src={entry.candidate.thumbnail} alt="" width="72" height="108" loading="lazy" /></Show><span class="min-w-0"><strong class="block text-sm leading-5">{entry.candidate.title}</strong><small class="mt-1 block font-mono text-[9px] uppercase tracking-[.08em] opacity-60">{Math.round(entry.score * 100)}% match · {entry.aniListTitle}</small><span class="mt-3 block font-mono text-[9px] uppercase tracking-[.12em]">Use this title →</span></span></button>}</For></div>
  </section>
}
